export const routes = {
    home: '/',
    shop: '/shop',
    product: '/product',
    productList: '/product-list',
    premium: '/premium',
    selling: '/account/selling',
    purchases: '/account/purchases',
    membership: '/account/membership',
    storeInfo: '/account/store-info',
    contact: '/contact',
    privacy: '/privacy',
    terms: '/terms',
    faqs: '/faqs',
    marketplace: '/marketplace',
    marketplaceStore: '/marketplace-store',
};
